const donations = [
  {
    donation_ID: "DON-00032",
    donorName: "Ajay",
    residence: "Kolkata",
    date_of_Donation: "11/9/2022",
    donation_Amount: 12000,
    cause: "Nepal Earthquake",
  },
  {
    donation_ID: "DON-00033",
    donorName: "Pranshu",
    residence: "Delhi",
    date_of_Donation: "05/19/2021",
    donation_Amount: 300,
    cause: "Yass Cyclone",
  },
  {
    donation_ID: "DON-00035",
    donorName: "Sami",
    residence: "Thane",
    date_of_Donation: "07/05/2020",
    donation_Amount: 2800,
    cause: "Amphan Cyclone",
  },
  {
    donation_ID: "DON-00036",
    donorName: "Rajendra",
    residence: "Jaipur",
    date_of_Donation: "07/06/2020",
    donation_Amount: 1500,
    cause: "Amphan Cyclone",
  },
  {
    donation_ID: "DON-00048",
    donorName: "Sreetama",
    residence: "Jaipur",
    date_of_Donation: "07/06/2020",
    donation_Amount: 1500,
    cause: "Amphan Cyclone",
  },
  {
    donation_ID: "DON-00049",
    donorName: "Pratush",
    residence: "Pune",
    date_of_Donation: "02/05/2018",
    donation_Amount: 500,
    cause: "Maharastra Floods",
  },
  {
    donation_ID: "DON-00051",
    donorName: "Pralay",
    residence: "Bangalore",
    date_of_Donation: "06/21/2018",
    donation_Amount: 20000,
    cause: "West bengal Cyclone",
  },
  {
    donation_ID: "DON-00052",
    donorName: "Sneha",
    residence: "Durgapur",
    date_of_Donation: "03/23/2018",
    donation_Amount: 20000,
    cause: "West bengal Cyclone",
  },
  {
    donation_ID: "DON-00054",
    donorName: "Vishal",
    residence: "Patna",
    date_of_Donation: "06/12/2018",
    donation_Amount: 8500,
    cause: "Maharastra Floods",
  },
  {
    donation_ID: "DON-00055",
    donorName: "Vijay",
    residence: "Darjeeling",
    date_of_Donation: "03/01/2018",
    donation_Amount: 150,
    cause: "Maharastra Floods",
  },
  {
    donation_ID: "DON-00056",
    donorName: "Bani",
    residence: "Gangtok",
    date_of_Donation: "02/05/2018",
    donation_Amount: 1200,
    cause: "Assam Floods",
  },
  {
    donation_ID: "DON-00068",
    donorName: "Vinayak",
    residence: "Delhi",
    date_of_Donation: "02/06/2018",
    donation_Amount: 2000,
    cause: "Fire break",
  },
  {
    donation_ID: "DON-00069",
    donorName: "Darshal",
    residence: "Noida",
    date_of_Donation: "02/06/2018",
    donation_Amount: 1000,
    cause: "Bridge Collapse",
  },
];

export default donations;
